[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"
[dev]
  targetPort = 5173

[[redirects]]
  from ="/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
